/*
 * This file is only a default template to satisfy the imports within the app!
 * This file is replaced by angular with the "src/environments/environment.generated.ts"
 *
 * The env is generated by: tools/update-angular-environment.js
 */


interface AppEnvironment {
    readonly mapboxApiKey: string;
    readonly production: boolean;
}
export const environment: AppEnvironment = {
    mapboxApiKey: "<mapbox-api-key>",
    production: false
};
